version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      eslint:
        patterns:
          - "eslint"
          - "@eslint/*"
          - "eslint-*"
      typescript:
        patterns:
          - "typescript"
          - "@typescript-eslint/*"
          - "@types/*"
      rollup:
        patterns:
          - "rollup"
          - "@rollup/*"
          - "rollup-*"
      vitest:
        patterns:
          - "vitest"
          - "@vitest/*"
      prettier:
        patterns:
          - "prettier"
          - "eslint-config-prettier"
          - "eslint-plugin-prettier"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
