name: Mock TypeORM

on:
  push:
    branches:
      - master
      - dev
      - "feature/**"
  pull_request:
    branches:
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: "package.json"
      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-node-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: pnpm install

      - name: Run Lint
        run: pnpm run lint

      - name: Run Tests
        run: pnpm run test
